### ISSUE TITLE
Invalid Literal for int()

### ISSUE THREAD

**Issue by chuck-confluent** [DavidSamir/credit-card-generator#3]
Hey David, thanks for putting together this little credit card generator. It's great for setting up demos!

I came across this funny error that only shows up once in a blue moon:
```
Traceback (most recent call last):
  File "creditcard_send.py", line 31, in <module>
    curr_credit_card = str(rand.choice([ccard.visa(), ccard.americanexpress()]))
  File "/workspace/.venv/lib/python3.8/site-packages/ccard/__init__.py", line 46, in americanexpress
    return get_number(FILES['americanexpress'])
  File "/workspace/demo-database-modernization/.venv/lib/python3.8/site-packages/ccard/__init__.py", line 33, in get_number
    return int(line)
ValueError: invalid literal for int() with base 10: '374431730205122",    "375607403241135\n'
```

Seems like the `line` in the `get_number` method sometimes, for whatever reason, has a little parsing issue.

I should add that I'm generating these things 1 per second in a while loop and after running this demo for a good long while, this is the first time I'm seeing this error. It's quite transient.

**Comment by DavidSamir** [comment]
thanks for taking the time to document the error :D 
it's a bit unexpected but we'll look into it, 

and if you managed to understand what's the reason it's behaving that way, that would be super helpful for us 
thanks again.

**Comment by kaloyan13** [comment]
Line 19998 in FILES['american_express'] has wrong format:
[374431730205122",    "375607403241135](https://github.com/DavidSamir/credit-card-generator/blob/b3f56da2ded4cfca744c213b68b7575d0f50de9f/ccard/americanexpress#L19998)

Made a pull request here #4
